name: Lock Issues

on:
  schedule:
    - cron: '15 * * * *'

jobs:
  lock:
    name: Lock Issues
    runs-on: ubuntu-latest
    steps:
      - name: Lock Issues
        uses: dessant/lock-threads@v2
        with:
          github-token: ${{ github.token }}
          issue-lock-reason: ''
          process-only: issues
